---

# SPDX-FileCopyrightText: 2021 Samsung Electronics
#
# SPDX-License-Identifier: Apache-2.0

- name: Converge
  hosts: all
  gather_facts: true
  roles:
    - role: pre-install
      inventory_path: /home/kuberef/inventory
