---

# SPDX-FileCopyrightText: 2021 Samsung Electronics
#
# SPDX-License-Identifier: Apache-2.0

dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c ../../../.yamllint .
  ansible-lint
platforms:
  - name: centos_7
    image: centos:7
provisioner:
  name: ansible
verifier:
  name: testinfra
  lint:
    name: flake8
