---
# GitLab CI config file to deploy RI2 on baremetal infra
# and run RC2 compliance tests on the deployed platform.
# TODO add tox jobs

stages:
  - deploy_platform
  - run_compliance_tests

deploy:
  stage: deploy_platform
  tags:
    - ericsson-pod2
  script:
    - bash deploy.sh

runtestsuite:
  extends: deploy
  stage: run_compliance_tests
  tags:
    - ericsson-pod2
  script:
    - bash run_testsuite.sh
  when: on_success
