# SPDX-FileCopyrightText: 2021 Anuket contributors
#
# SPDX-License-Identifier: Apache-2.0

---
# GitLab CI config file to deploy RI2 on baremetal infra
# and run RC2 compliance tests on the deployed platform.
# TODO add tox jobs

variables:
  S3_ENDPOINT_URL: https://storage.googleapis.com
  S3_DST_URL: s3://artifacts.opnfv.org/kuberef/${CI_COMMIT_SHORT_SHA}/${CI_JOB_NAME}-${CI_JOB_ID}
  HTTP_DST_URL: http://artifacts.opnfv.org/kuberef/${CI_COMMIT_SHORT_SHA}/${CI_JOB_NAME}-${CI_JOB_ID}
  TEST_DB_URL: http://testresults.opnfv.org/test/api/v1/results
  TEST_DB_EXT_URL: http://testresults.opnfv.org/test/api/v1/results
  NODE_NAME: intel-pod19
  BUILD_TAG: ${CI_COMMIT_SHORT_SHA}
  DEPLOY_SCENARIO: k8-nosdn-nofeature-noha

stages:
  - .pre
  - deploy_platform
  - functest-kubernetes-healthcheck
  - functest-kubernetes-benchmarking
  - functest-kubernetes-security
  - functest-kubernetes-smoke
  - functest-kubernetes-cnf
  - zip
  - .post

deploy:
  tags:
    - unh-ri2-pod1
  stage: deploy_platform
  script:
    - bash deploy.sh

k8s_quick:
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-healthcheck
  image: opnfv/functest-kubernetes-healthcheck:v1.21
  script:
    - run_tests -t k8s_quick -p -r

k8s_smoke:
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-healthcheck
  image: opnfv/functest-kubernetes-healthcheck:v1.21
  script:
    - run_tests -t k8s_smoke -p -r

xrally_kubernetes:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t xrally_kubernetes -p -r

k8s_conformance:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t k8s_conformance -p -r

k8s_conformance_serial:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t k8s_conformance_serial -p -r

sig_api_machinery:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_api_machinery -p -r

sig_api_machinery_serial:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_api_machinery_serial -p -r

sig_apps:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_apps -p -r

sig_apps_serial:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_apps_serial -p -r

sig_auth:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_auth -p -r

sig_cluster_lifecycle:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_cluster_lifecycle -p -r

sig_instrumentation:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_instrumentation -p -r

sig_network:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_network -p -r

sig_node:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_node -p -r

sig_scheduling_serial:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_scheduling_serial -p -r

sig_storage:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_storage -p -r

sig_storage_serial:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-smoke
  image: opnfv/functest-kubernetes-smoke:v1.21
  script:
    - run_tests -t sig_storage_serial -p -r

kube_hunter:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-security
  image: opnfv/functest-kubernetes-security:v1.21
  script:
    - run_tests -t kube_hunter -p -r

kube_bench_master:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-security
  image: opnfv/functest-kubernetes-security:v1.21
  script:
    - run_tests -t kube_bench_master -p -r

kube_bench_node:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-security
  image: opnfv/functest-kubernetes-security:v1.21
  script:
    - run_tests -t kube_bench_node -p -r

xrally_kubernetes_full:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-benchmarking
  image: opnfv/functest-kubernetes-benchmarking:v1.21
  script:
    - run_tests -t xrally_kubernetes_full -p -r

netperf:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-benchmarking
  image: opnfv/functest-kubernetes-benchmarking:v1.21
  script:
    - run_tests -t netperf -p -r

k8s_vims:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-cnf
  image: opnfv/functest-kubernetes-cnf:v1.21
  script:
    - run_tests -t k8s_vims -p -r

helm_vims:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-cnf
  image: opnfv/functest-kubernetes-cnf:v1.21
  script:
    - run_tests -t helm_vims -p -r

cnf_testsuite:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: functest-kubernetes-cnf
  image: opnfv/functest-kubernetes-cnf:v1.21
  script:
    - run_tests -t cnf_testsuite -p -r

zip:
  only:
    - schedules
  tags:
    - intel-pod19-docker
  stage: zip
  variables:
    S3_DST_URL: s3://artifacts.opnfv.org/kuberef/
    HTTP_DST_URL: http://artifacts.opnfv.org/kuberef/
  image: opnfv/functest-kubernetes-healthcheck:v1.21
  script:
    - zip_campaign
