# SPDX-FileCopyrightText: 2021 Anuket contributors
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Write BMRA inventory config
  template:
    src: "inventory.j2"
    dest: "{{ kuberef_root }}/sw_config/bmra/inventory.ini"

- name: Write BMRA kube-node config
  template:
    src: "kube-node.j2"
    dest: "{{ kuberef_root }}/sw_config/bmra/kube-node.yml"

- name: Write BMRA all config
  template:
    src: "all.j2"
    dest: "{{ kuberef_root }}/sw_config/bmra/all.yml"
