---

# SPDX-FileCopyrightText: 2021 Anuket contributors
# SPDX-FileCopyrightText: 2021 Ericsson AB and others
#
# SPDX-License-Identifier: Apache-2.0

- hosts: localhost
  connection: local
  gather_facts: false
  become: false

  roles:
    - role: bmra-config
