---
# SPDX-license-identifier: Apache-2.0
##############################################################################
# Copyright (c) 2020 Samsung Electronics
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Apache License, Version 2.0
# which accompanies this distribution, and is available at
# http://www.apache.org/licenses/LICENSE-2.0
##############################################################################

- name: Install requirements on nodes
  hosts: baremetal
  gather_facts: true
  roles:
    - role: configure-vms

# vim: set ts=2 sw=2 expandtab:
