---

# SPDX-FileCopyrightText: 2021 Samsung Electronics
#
# SPDX-License-Identifier: Apache-2.0

- name: Install requirements on nodes
  hosts: all,!localhost
  gather_facts: false
  roles:
    - role: pre-install
